jobs:
  test:
    name: CI on Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: ./mvnw -V --no-transfer-progress clean package
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
      max-parallel: 64
    timeout-minutes: 10
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
